name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-cache-${{ hashFiles('stack.yaml', 'package.yaml') }}
      - name: Build + test
        run: stack test --coverage

      - name: Run tomcab
        run: stack exec tomcab

      - name: Check that files are unmodified
        run: git diff --exit-code

      # upload coverage data
      - name: Generate coverage data
        run: stack install hpc-lcov && hpc-lcov
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info

  lint:
    runs-on: ubuntu-latest
    env:
      FOURMOLU_VERSION: '0.7.0.1'
    steps:
      - uses: actions/checkout@v2

      - name: Install fourmolu
        run: |
          curl -sSL \
            "https://github.com/fourmolu/fourmolu/releases/download/v${FOURMOLU_VERSION}/fourmolu-${FOURMOLU_VERSION}-linux-x86_64" \
            -o /usr/local/bin/fourmolu
          chmod +x /usr/local/bin/fourmolu
      - name: Run fourmolu
        run: fourmolu -m check $(git ls-files '*.hs')

  check_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-check_sdist-${{ hashFiles('stack.yaml', 'package.yaml') }}
      - name: Create sdist bundle
        run: stack sdist --test-tarball --tar-dir .
      - uses: actions/upload-artifact@v3
        with:
          name: tomcab-sdist
          path: tomcab-*.tar.gz
